Send email with office365
hoshmy/SoftwareUtilities pull request #12
Opened 2022-07-19 06:51 UTC by michal24509

add send email to SoftwareUtilities

2022-07-20 08:43 UTC, hChemouni requested changes

2022-07-20 08:43 UTC, hChemouni commented on api/email/send_email.py
> +        self._connection = self.init_connection()
It's not necessary

2022-07-20 08:43 UTC, hChemouni commented on api/email/send_email.py
>              Logger().warning(f"send email function get error {ex}")
Add name of function in warning as SendEmail.send_email have error {ex}

2022-07-20 10:51 UTC, hChemouni requested changes
Change name of to email_client

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +class SendEmail:
```suggestion
class EmailClient
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +
Remove this blank line

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +    def init_connection(self):
set this function as protected
```suggestion
    def _init_connection(self):
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +    def __init__(self, user_name, password):
```suggestion
    def __init__(self, _user_name, _password):
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +    def create_massage(self, recipient_address, subject, body):
```suggestion
    def _create_massage(self, _recipient_address, _subject, _body):
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +        mimemsg = self.create_massage(recipient_address, subject, body)
```suggestion
        mime_message = self.create_massage(_recipient_address=_recipient_address, _subject=_subject, _body=_body)
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +    def send_email(self, recipient_address, subject, body):
```suggestion
    def send_email(self, _recipient_address, _subject, _body):
```

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +            Logger().warning(f"SendEmail.send_email have error {ex}")
Update with the new name of class

2022-07-20 10:51 UTC, hChemouni commented on api/email/send_email.py
> +        time.sleep(2)
Put all code in the try except email_was_successfully_sent.
Change it to be false in default and update to true only in end of try

2022-07-21 07:04 UTC, hChemouni requested changes
Change name of file to be email_client

2022-07-21 07:04 UTC, hChemouni commented on api/email/send_email.py
> +            connection.send_message(mimemsg)
What send email function return ? you need check it and depend of response email_was_successfully_sent to be True or False

2022-07-21 09:17 UTC, hChemouni commented on api/email/send_email.py
> +            time.sleep(2)
Add explanation why you add the sleep

2022-07-24 07:46 UTC, hChemouni commented on api/email/send_email.py
> +            mimemsg = self._create_massage(_recipient_address, _subject, _body)
```suggestion
            mime_message= self._create_massage(_recipient_address, _subject, _body)
```

2022-07-24 07:54 UTC, hChemouni requested changes

2022-07-24 07:54 UTC, hChemouni commented on api/email/send_email.py
> +            mimemsg = self._create_massage(_recipient_address, _subject, _body)
You not change it

2022-07-24 07:54 UTC, hChemouni commented on api/email/send_email.py
> +        if connection is not None:
Why you check it ?

2022-07-24 16:12 UTC, michal24509 commented on api/email/send_email.py
> +        if connection is not None:
because if the connection fail the connection is none  and it's passible to quit none

2022-07-24 17:13 UTC, hChemouni commented on api/email/send_email.py
> +        if connection is not None:
it's possible or impossible to quit None ?

2022-07-24 18:38 UTC, michal24509 commented on api/email/send_email.py
> +        if connection is not None:
impossible

2022-07-25 05:44 UTC, hChemouni approved these changes

2022-07-25 05:45 UTC, merged