mongo_db
hoshmy/SoftwareUtilities pull request #24
Opened 2023-02-07 07:46 UTC by michal24509

2023-02-07 08:05 UTC, hadassaCh requested changes

2023-02-07 08:05 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +    def get(self, keys: list):
you implement the get and set in another PR ?

2023-02-07 08:11 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +        if db_user_name is None:
Add use_local_db variable in configuration to detect which connection string db to return, insteas use `db_user_name`

2023-02-07 11:13 UTC, michal24509 commented on db/mongo_db/mongo_db_client.py
> +    def get(self, keys: list):
yes I will  do it after create table

2023-02-07 14:59 UTC, hadassaCh requested changes

2023-02-07 14:59 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +        env_variable = _configuration.get('db_password')
The env_variable need retrieved before using MongoDBClient.
in configuration is sended the password.

2023-02-07 14:59 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +    mongo = MongoDBClient(_name='test_db', _configuration=db_config)
update the main

2023-02-08 10:38 UTC, hadassaCh requested changes

2023-02-08 10:38 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +        self._client.get_collection(_table_name)
what this function does ? it was not return anything

2023-02-08 16:28 UTC, hadassaCh requested changes

2023-02-08 16:28 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +from pymongo import MongoClient
You need update the requiement.txt file ?

2023-02-08 16:28 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +    def set(self, key: str, value: dict, _table_name) -> bool:
you are not update the change

2023-02-09 06:37 UTC, hadassaCh requested changes

2023-02-09 06:37 UTC, hadassaCh commented on db/mongo_db/mongo_db_client.py
> +    def get_table_by_name(self, _table_name):
This function already exist in line 33

2023-02-09 08:32 UTC, merged